#!/bin/bash
# FILENAME:  run_x1t_once
#************************************************************************
#*This file defines one run action to be performed on an individual file*
#*produced  in the listfile. Specifically the MC code to be used in Ln15*
#*It takes  input as defined in Ln72 of the list file.                  *
#*                                                                      *
#*$1 is the output file to be produced by the code                      *
#*$2 is the number of events to simulate                                *
#*                                                                      *
#************************************************************************
echo " "
echo "Job started on `hostname` at `date`"
echo " "
. /home/jpienaa/.bashrc
~/G4WORKDIR/bin/Linux-g++/./NSDNeutronGenerator -p ~/JP_Purdue/macros/Fluxpreinit.mac -f ~/JP_Purdue/macros/NeutronGenerator.mac -n $2 -o $1
rm ~/JP_Purdue/STDIN.*
echo " "
echo "Job Ended at `date`"
echo " "
