#!/bin/bash
# FILENAME:  run_x1t_once
#************************************************************************
#*This file defines one run action to be performed on an individual file*
#*produced  in the listfile. Specifically the MC code to be used in Ln15*
#*and the processing code to be used in Ln16. It takes  input as defined*
#*in Ln72 of the list file.                                             *
#*                                                                      *
#*$1 is the output file to be produced by the code                      *
#*$2 is the number of events to simulate                                *
#*$3 is the input file to be used by the processing code                *
#*$4 is the seperation between the detectors                            *
#*$5 is the angle between the first and second detectors                *
#*$6 is the distance between the first detector and the NG (Centres)    * 
#*                                                                      *
#*Additional input have to do with the processing code being used and   *
#*should be adjusted accordingly.                                       *
#************************************************************************
echo " "
echo "Job started on `hostname` at `date`"
echo " "
. /home/jpienaa/.bashrc
~/G4WORKDIR/bin/Linux-g++/./NSDNeutronGenerator -p ~/JP_Purdue/macros/Energypreinit.mac -f ~/JP_Purdue/macros/NeutronGenerator.mac -n $2 -o $1
~/JP_Purdue/Energy/./DoubleScatter -p $3 -s $4 -a $5 -d $6 
#sleep 2
#rm $1
rm ~/JP_Purdue/STDIN.*
echo " "
echo "Job Ended at `date`"
echo " "
