#Determine if flux calibration (Flux) or energy measurement (Energy) is needed
/Purdue/detector/setMeasurement Flux

#Set position of First Deetector
/Purdue/detector/FirstDetectorCoord 0 -260 -1598 mm
#/Purdue/detector/FirstDetectorCoord 0 600 -848 mm
#261

#For Energy measurements 2nd/3rd detector positions determined relative to 1st
#/Purdue/detector/setDetectorSeperation 1000 mm
#/Purdue/detector/setDetectorAngle 45

#For flux measurements set position of 2nd/3rd detector individually
/Purdue/detector/SecondDetectorCoord 260 0 -1598 mm	
/Purdue/detector/ThirdDetectorCoord -260 0 -1598 mm
#158

#/Purdue/detector/SecondDetectorCoord 600 0 -898 mm	
#/Purdue/detector/ThirdDetectorCoord -600 0 -898 mm

#Set wether the Lead Sleeves are to be present or not. Default is true.
/Purdue/detector/setLeadSleeves true



