# Andrew, Jacques 
# Example code for making mono-energetic DD neutrons 
# Must be run with NeutronGenerator option in the pre-initialisation macro!!

/vis/open OGLIX
/vis/drawVolume
/tracking/storeTrajectory 3
/vis/scene/add/trajectories
/vis/scene/add/hits
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointThetaPhi 180 0
/vis/viewer/panTo 100 50 mm
/vis/viewer/zoom 3

#No RunActionMessenger as yet
#/run/random/setRandomSeed 0

#For Mono-energetic Neutrons
/xe/gun/particle neutron
/xe/gun/energy 2500 keV
/xe/gun/angtype iso

/xe/gun/type   Volume  
/xe/gun/shape  Cylinder
#/xe/gun/center 0 0 -938 mm
/xe/gun/center 0 0 -898 mm
/xe/gun/radius 9.0 mm 
/xe/gun/halfz  21.5 mm
#21.5cm

#For Energy Spectrum of Cf252
#/xe/gun/energytype Spectrum
#/xe/gun/energyspectrum /home/jpienaa/JP_Purdue/macros/cf252_neutron.dat
#/xe/gun/particle neutron
#/xe/gun/angtype iso

#/run/beamOn/10000


#/process/em/fluo true
#/process/em/auger true
#/physics_engine/neutron/energyLimit 1.e-10 eV
#/physics_engine/neutron/timeLimit 999999999 s

#/run/verbose 1
#/event/verbose 1
#/tracking/verbose 1
#/control/verbose 1
